### ISSUE TITLE
The readme instructions could be copy & paste?

### ISSUE THREAD

**Issue by uebmaster** [colisee/docker-librebooking#6]
I am trying to install an instance of librebooking, but when i try this (copy & paste):

docker-compose: simple setup with docker secrets
As an alternative to passing sensitive information via environment variables, _FILE may be appended to some of the previously listed environment variables, causing the initialization script to load the values for those variables from files present in the container. In particular, this can be used to load passwords from Docker secrets stored in /run/secrets/<secret_name> files. The following setup is also meant to be run behind an existing reverse proxy.

**Create a docker-compose.yml file from the following sample and adapt it to your needs and standards:**

version: "3.7"

services:
  db:
    image: linuxserver/mariadb
    container_name: librebooking-db
    restart: always
    networks:
      - net
    volumes:
      - vol-db:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=
      - MYSQL_DATABASE=librebooking
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/db_root_pwd
      - MYSQL_USER=lb_user
      - FILE__MYSQL_PASSWORD=/run/secrets/db_user_pwd
    secrets:
      - db_root_pwd
      - db_user_pwd
  app:
    image: colisee/librebooking
    container_name: librebooking
    restart: always
    depends_on:
      - db
    networks:
      - net
    ports:
      - "8080:80"
    volumes:
      - vol-app:/var/www/html
    environment: 
      - TZ=
      - LB_DB_HOST=lb-db
      - LB_DB_NAME=librebooking
      - LB_INSTALL_PWD_FILE=/run/secrets/lb_install_pwd
      - LB_DB_USER=lb_user
      - LB_DB_USER_PWD_FILE=/run/secrets/lb_user_pwd
    secrets:
      - lb_install_pwd
      - lb_user_pwd

volumes:
  vol-db:
    name: librebooking-db_data
  vol-app:
    name: librebooking_html

networks:
  net:
    name: librebooking

secrets:
  db_root_pwd:
    file: ./db_root_pwd.txt   # put the MariaDB root password in this file
  db_user_pwd:
    file: ./db_user_pwd.txt   # put the MariaDB user password in this file
  lb_user_pwd:
    file: ./db_user_pwd.txt
  lb_install_pwd:
    file: ./lb_install_pwd.txt   # put the app installation password in this file

**Then run the following commands:**

echo 'your_Mariadb_root_password' > db_root_pwd.txt;
echo 'your_Mariadb_user_password' > db_user_pwd.txt;
echo 'your_Librebooking_installation_password' > lb_install_pwd.txt;
docker-compose up --detach

**i got this:**

![image](https://user-images.githubusercontent.com/5565506/197648652-e5f32b5a-cc10-4c10-9c04-7c29c720956d.png)

**What is wrong?**

I've been debuging but i can't make it works.

**Comment by colisee** [comment]
Thank you very much for reporting this issue that I am able to reproduce on my side as well.

I already identified 1 error in my documentation for file docker-compose.yml:
I should have written: `LB_DB_HOST=db` instead of `LB_DB_HOST=lb-db`

Then I found out that somehow I have a SQL access problem when I use docker-compose.yml with docker secrets. However, if I use the simple setup without docker secrets, I have no SQL access problem. I need to further investigate this point and I will keep the issue open.

In the meantime, if you need to go ahead while I am working on it, please switch to the simple setup (without docker secrets).

**Comment by colisee** [comment]
Please proceed as follows:
1. Stop the containers with `docker-compose down`
2. Remove the volumes with `docker volume rm librebooking_html librebooking-db_data`
3. Modify your file docker-compose.yml 
4. Lanch the containers with `docker-compose up --detach`

**Comment by colisee** [comment]
I found the error.
One must use `echo -n` to initialize the secrets text files. For instance:
`echo -n 'your_Mariadb_root_password' > db_root_pwd.txt`

README.md file was corrected.
